// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhcYUlIRH2I8hZPp1fKuN5aScrTQA08FA',
    appId: '1:913574064965:web:f65c68e5b3a5e33516042c',
    messagingSenderId: '913574064965',
    projectId: 'fir-auth-7b0d4',
    authDomain: 'fir-auth-7b0d4.firebaseapp.com',
    storageBucket: 'fir-auth-7b0d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPMDkSKNypfj_BHaJBuLSObQ2R-cax_Uo',
    appId: '1:913574064965:android:916d4697f5ef281f16042c',
    messagingSenderId: '913574064965',
    projectId: 'fir-auth-7b0d4',
    storageBucket: 'fir-auth-7b0d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEZma8G-vhFyRdMASi2xB00fheWKYZYJc',
    appId: '1:913574064965:ios:a1685d35994ff10516042c',
    messagingSenderId: '913574064965',
    projectId: 'fir-auth-7b0d4',
    storageBucket: 'fir-auth-7b0d4.appspot.com',
    iosClientId: '913574064965-k7behetri73ahndp59np5d2sv1tmstts.apps.googleusercontent.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );

}